name: R-CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: Rscript -e 'install.packages(c("data.table","yaml","TTR","xts","PerformanceAnalytics","testthat"), repos="https://cran.rstudio.com")'

    - name: Run tests
      run: Rscript -e 'library(testthat); test_dir("tests/testthat")'

    - name: Run baseline backtest
      run: Rscript -e 'source("R/03_baseline_backtest.R")'