name: R-CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'packages <- c("data.table","yaml","TTR","xts","PerformanceAnalytics","testthat","quantmod"); 
                      need <- packages[!sapply(packages, requireNamespace, quietly = TRUE)];
                      if(length(need)) install.packages(need, repos="https://cran.rstudio.com")'

      - name: Run tests
        run: Rscript -e 'library(testthat); test_dir("tests/testthat")'

      - name: Run baseline backtest (main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: Rscript -e 'source("R/03_baseline_backtest.R")'
